name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build 
      run: gcc -o giftcardreader giftcardreader.c 
    - name: Crash 1 on GiftCardReader 
      run: ./giftcardreader 1 ./tests/crash1.gft 
    - name: Crash 2 on GiftCardReader 
      run: ./giftcardreader 1 ./tests/crash2.gft
    - name: Hang Attack on GiftCard Reader 
      run: ./giftcardreader 1 ./tests/hang.gft
